### PR TITLE
Jshackell beta

### PR DESCRIPTION
**Pull request by violinshack**
updated readme and Jenkinsfile to use "project" instead of workspace, removed Test Runner, updated link to (not yet published) Dev Guide.

### CODE REVIEW

**Comment by wadewegner** [comment]
@violinshack I think we want to merge into beta branch, right?

**Comment by violinshack** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Yes!  Thx. 


Sent from my iPhone.

On Monday, June 19, 2017, 3:30 PM, Wade Wegner <notifications@github.com> wrote:


@violinshack I think we want to merge into beta branch, right?

**Comment by violinshack** [comment]
Sorry about that, yes, merge to beta.  I think I modified my pull request correctly, I'm still a newbie...

**Comment by wadewegner** [comment]
You did great. Thanks @violinshack!

**Pull request merged**
